/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lspr_graph_RealDataActivity */

#ifndef _Included_com_lspr_graph_RealDataActivity
#define _Included_com_lspr_graph_RealDataActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lspr_graph_RealDataActivity_MODE_PRIVATE
#define com_lspr_graph_RealDataActivity_MODE_PRIVATE 0L
#undef com_lspr_graph_RealDataActivity_MODE_WORLD_READABLE
#define com_lspr_graph_RealDataActivity_MODE_WORLD_READABLE 1L
#undef com_lspr_graph_RealDataActivity_MODE_WORLD_WRITEABLE
#define com_lspr_graph_RealDataActivity_MODE_WORLD_WRITEABLE 2L
#undef com_lspr_graph_RealDataActivity_MODE_APPEND
#define com_lspr_graph_RealDataActivity_MODE_APPEND 32768L
#undef com_lspr_graph_RealDataActivity_MODE_MULTI_PROCESS
#define com_lspr_graph_RealDataActivity_MODE_MULTI_PROCESS 4L
#undef com_lspr_graph_RealDataActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_lspr_graph_RealDataActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_lspr_graph_RealDataActivity_BIND_AUTO_CREATE
#define com_lspr_graph_RealDataActivity_BIND_AUTO_CREATE 1L
#undef com_lspr_graph_RealDataActivity_BIND_DEBUG_UNBIND
#define com_lspr_graph_RealDataActivity_BIND_DEBUG_UNBIND 2L
#undef com_lspr_graph_RealDataActivity_BIND_NOT_FOREGROUND
#define com_lspr_graph_RealDataActivity_BIND_NOT_FOREGROUND 4L
#undef com_lspr_graph_RealDataActivity_BIND_ABOVE_CLIENT
#define com_lspr_graph_RealDataActivity_BIND_ABOVE_CLIENT 8L
#undef com_lspr_graph_RealDataActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_lspr_graph_RealDataActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_lspr_graph_RealDataActivity_BIND_WAIVE_PRIORITY
#define com_lspr_graph_RealDataActivity_BIND_WAIVE_PRIORITY 32L
#undef com_lspr_graph_RealDataActivity_BIND_IMPORTANT
#define com_lspr_graph_RealDataActivity_BIND_IMPORTANT 64L
#undef com_lspr_graph_RealDataActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_lspr_graph_RealDataActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_lspr_graph_RealDataActivity_CONTEXT_INCLUDE_CODE
#define com_lspr_graph_RealDataActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_lspr_graph_RealDataActivity_CONTEXT_IGNORE_SECURITY
#define com_lspr_graph_RealDataActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_lspr_graph_RealDataActivity_CONTEXT_RESTRICTED
#define com_lspr_graph_RealDataActivity_CONTEXT_RESTRICTED 4L
#undef com_lspr_graph_RealDataActivity_RESULT_CANCELED
#define com_lspr_graph_RealDataActivity_RESULT_CANCELED 0L
#undef com_lspr_graph_RealDataActivity_RESULT_OK
#define com_lspr_graph_RealDataActivity_RESULT_OK -1L
#undef com_lspr_graph_RealDataActivity_RESULT_FIRST_USER
#define com_lspr_graph_RealDataActivity_RESULT_FIRST_USER 1L
#undef com_lspr_graph_RealDataActivity_DEFAULT_KEYS_DISABLE
#define com_lspr_graph_RealDataActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_lspr_graph_RealDataActivity_DEFAULT_KEYS_DIALER
#define com_lspr_graph_RealDataActivity_DEFAULT_KEYS_DIALER 1L
#undef com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SHORTCUT
#define com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_lspr_graph_RealDataActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_lspr_1graph_RealDataActivity_testInit
  (JNIEnv *, jobject);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetInteragtion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lspr_1graph_RealDataActivity_testGetInteragtion
  (JNIEnv *, jobject);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetSpectrumType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lspr_1graph_RealDataActivity_testGetSpectrumType
  (JNIEnv *, jobject);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetSpectrumNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lspr_1graph_RealDataActivity_testGetSpectrumNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lspr_1graph_RealDataActivity_testGetLength
  (JNIEnv *, jobject);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetSpectrumValues
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_lspr_1graph_RealDataActivity_testGetSpectrumValues
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lspr_graph_RealDataActivity
 * Method:    testGetWavelengthValues
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_lspr_1graph_RealDataActivity_testGetWavelengthValues
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
