/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lspr_graph_RealDataActivity_MyThread */

#ifndef _Included_com_lspr_graph_RealDataActivity_MyThread
#define _Included_com_lspr_graph_RealDataActivity_MyThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_lspr_graph_RealDataActivity_MyThread_MAX_PRIORITY
#define com_lspr_graph_RealDataActivity_MyThread_MAX_PRIORITY 10L
#undef com_lspr_graph_RealDataActivity_MyThread_MIN_PRIORITY
#define com_lspr_graph_RealDataActivity_MyThread_MIN_PRIORITY 1L
#undef com_lspr_graph_RealDataActivity_MyThread_NORM_PRIORITY
#define com_lspr_graph_RealDataActivity_MyThread_NORM_PRIORITY 5L
#ifdef __cplusplus
}
#endif
#endif
